// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package signerv4 provides an implementation of AWS Signature Version 4 signing.
// It allows signing HTTP requests using AWS credentials
package signerv4_test

import (
	"io"
	"log"
	"net/http"
	"strings"
	"testing"
	"time"

	"github.com/google/osv-scalibr/veles/secrets/common/signerv4"
)

const (
	ACCESS_KEY_ID     = "AKIAIOSFODNN7EXAMPLE"
	SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
)

// TestSign verifies that the signature generated using the signerv4 package corresponds to the one generated by
// github.com/aws/aws-sdk-go-v2.
//
// The signature was extracted using both the s3 and sts client with the `config.WithClientLogMode(aws.LogRequest)`
func TestSign(t *testing.T) {
	time1, err := time.Parse("20060102T150405Z", "20251107T181714Z")
	if err != nil {
		log.Fatal(err)
	}

	time2, err := time.Parse("20060102T150405Z", "20251107T181716Z")
	if err != nil {
		log.Fatal(err)
	}

	testcases := []struct {
		name          string
		service       string
		req           func() *http.Request
		time          time.Time
		reqID         string
		signedHeaders []string
		want          string
	}{
		{
			name:    "s3 ListBuckets api",
			service: "s3",
			req: func() *http.Request {
				req, _ := http.NewRequestWithContext(t.Context(), http.MethodGet, "https://s3.us-east-1.amazonaws.com/?x-id=ListBuckets", nil)
				req.Header.Set("Accept-Encoding", "identity")
				req.Header.Set("Host", "s3.us-east-1.amazonaws.com")
				req.Header.Set("User-Agent", "aws-sdk-go-v2/1.39.6 ua/2.1 os/macos lang/go#1.25.4 md/GOOS#darwin md/GOARCH#arm64 api/s3#1.90.0 m/E,e")
				return req
			},
			time:  time1,
			reqID: "6c8a4c0d-23ef-4471-be71-14c80ec8f680",
			signedHeaders: []string{
				"accept-encoding", "amz-sdk-invocation-id", "amz-sdk-request",
				"host", "x-amz-content-sha256", "x-amz-date",
			},
			want: "Signature=0fe2b0caa3bbe457ebba25c502c6094e640c8ee4308100ce647e4497bad5ce7f",
		},
		{
			name:    "sts GetCallerIdentity action",
			service: "sts",
			req: func() *http.Request {
				req, _ := http.NewRequestWithContext(
					t.Context(), http.MethodPost,
					"https://sts.us-east-1.amazonaws.com/",
					io.NopCloser(strings.NewReader("Action=GetCallerIdentity&Version=2011-06-15")),
				)
				req.Header.Set("Host", "sts.us-east-1.amazonaws.com")
				req.Header.Set("User-Agent", "aws-sdk-go-v2/1.39.6 ua/2.1 os/macos lang/go#1.25.4 md/GOOS#darwin md/GOARCH#arm64 api/sts#1.39.1 m/E,e")
				req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
				req.Header.Set("Accept-Encoding", "gzip")
				return req
			},
			time: time2,
			signedHeaders: []string{
				"amz-sdk-invocation-id", "amz-sdk-request", "content-length",
				"content-type", "host", "x-amz-date",
			},
			reqID: "2f0054ff-8975-4c0d-8168-f4446fe4d76b",
			want:  "Signature=1789c751a9d360e0ec1f75e38f7768ab05a382cdf34b40d553fa72d53e7a8a08",
		},
	}

	for _, tt := range testcases {
		t.Run(tt.name, func(t *testing.T) {
			s := signerv4.New(signerv4.Config{
				Service:       tt.service,
				Region:        "us-east-1",
				Now:           func() time.Time { return tt.time },
				SignedHeaders: tt.signedHeaders,
				UUID:          func() string { return tt.reqID },
			})

			req := tt.req()
			err := s.Sign(req, ACCESS_KEY_ID, SECRET_ACCESS_KEY)
			if err != nil {
				t.Errorf("Sign(%v) error: %v; want error presence = false", req, err)
			}

			authHeader := req.Header.Get("Authorization")
			if !strings.Contains(authHeader, tt.want) {
				t.Errorf("Authorization header: %q; does not contain the correct signature: %q, \n\n%v", authHeader, tt.want, req.Header)
			}
		})
	}
}
