//
// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v6.33.1
// source: proto/config.proto

package config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The maximum file size the plugin will process.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	// Config values that only apply to a single plugin.
	PluginSpecific []*PluginSpecificConfig `protobuf:"bytes,2,rep,name=plugin_specific,json=pluginSpecific,proto3" json:"plugin_specific,omitempty"`
}

func (x *PluginConfig) Reset() {
	*x = PluginConfig{}
	mi := &file_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginConfig) ProtoMessage() {}

func (x *PluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginConfig.ProtoReflect.Descriptor instead.
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *PluginConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

func (x *PluginConfig) GetPluginSpecific() []*PluginSpecificConfig {
	if x != nil {
		return x.PluginSpecific
	}
	return nil
}

type PluginSpecificConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Config:
	//
	//	*PluginSpecificConfig_GoBinary
	//	*PluginSpecificConfig_Govulncheck
	//	*PluginSpecificConfig_Archive
	//	*PluginSpecificConfig_Ova
	//	*PluginSpecificConfig_Vdi
	//	*PluginSpecificConfig_Vmdk
	Config isPluginSpecificConfig_Config `protobuf_oneof:"config"`
}

func (x *PluginSpecificConfig) Reset() {
	*x = PluginSpecificConfig{}
	mi := &file_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSpecificConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSpecificConfig) ProtoMessage() {}

func (x *PluginSpecificConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSpecificConfig.ProtoReflect.Descriptor instead.
func (*PluginSpecificConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{1}
}

func (m *PluginSpecificConfig) GetConfig() isPluginSpecificConfig_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (x *PluginSpecificConfig) GetGoBinary() *GoBinaryConfig {
	if x, ok := x.GetConfig().(*PluginSpecificConfig_GoBinary); ok {
		return x.GoBinary
	}
	return nil
}

func (x *PluginSpecificConfig) GetGovulncheck() *GovulncheckConfig {
	if x, ok := x.GetConfig().(*PluginSpecificConfig_Govulncheck); ok {
		return x.Govulncheck
	}
	return nil
}

func (x *PluginSpecificConfig) GetArchive() *ArchiveConfig {
	if x, ok := x.GetConfig().(*PluginSpecificConfig_Archive); ok {
		return x.Archive
	}
	return nil
}

func (x *PluginSpecificConfig) GetOva() *OVAConfig {
	if x, ok := x.GetConfig().(*PluginSpecificConfig_Ova); ok {
		return x.Ova
	}
	return nil
}

func (x *PluginSpecificConfig) GetVdi() *VDIConfig {
	if x, ok := x.GetConfig().(*PluginSpecificConfig_Vdi); ok {
		return x.Vdi
	}
	return nil
}

func (x *PluginSpecificConfig) GetVmdk() *VMDKConfig {
	if x, ok := x.GetConfig().(*PluginSpecificConfig_Vmdk); ok {
		return x.Vmdk
	}
	return nil
}

type isPluginSpecificConfig_Config interface {
	isPluginSpecificConfig_Config()
}

type PluginSpecificConfig_GoBinary struct {
	GoBinary *GoBinaryConfig `protobuf:"bytes,1,opt,name=go_binary,json=goBinary,proto3,oneof"`
}

type PluginSpecificConfig_Govulncheck struct {
	Govulncheck *GovulncheckConfig `protobuf:"bytes,2,opt,name=govulncheck,proto3,oneof"`
}

type PluginSpecificConfig_Archive struct {
	Archive *ArchiveConfig `protobuf:"bytes,3,opt,name=archive,proto3,oneof"`
}

type PluginSpecificConfig_Ova struct {
	Ova *OVAConfig `protobuf:"bytes,4,opt,name=ova,proto3,oneof"`
}

type PluginSpecificConfig_Vdi struct {
	Vdi *VDIConfig `protobuf:"bytes,5,opt,name=vdi,proto3,oneof"`
}

type PluginSpecificConfig_Vmdk struct {
	Vmdk *VMDKConfig `protobuf:"bytes,6,opt,name=vmdk,proto3,oneof"`
}

func (*PluginSpecificConfig_GoBinary) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Govulncheck) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Archive) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Ova) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Vdi) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Vmdk) isPluginSpecificConfig_Config() {}

type GoBinaryConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Enables extracting the module version from the Go binary content.
	VersionFromContent bool `protobuf:"varint,1,opt,name=version_from_content,json=versionFromContent,proto3" json:"version_from_content,omitempty"`
}

func (x *GoBinaryConfig) Reset() {
	*x = GoBinaryConfig{}
	mi := &file_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoBinaryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoBinaryConfig) ProtoMessage() {}

func (x *GoBinaryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoBinaryConfig.ProtoReflect.Descriptor instead.
func (*GoBinaryConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{2}
}

func (x *GoBinaryConfig) GetVersionFromContent() bool {
	if x != nil {
		return x.VersionFromContent
	}
	return false
}

type GovulncheckConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Path to the offline vuln DB to pass to govunlcheck. If empty,
	// the detector will query vulns from the net instead.
	OfflineVulnDbPath string `protobuf:"bytes,1,opt,name=offline_vuln_db_path,json=offlineVulnDbPath,proto3" json:"offline_vuln_db_path,omitempty"`
}

func (x *GovulncheckConfig) Reset() {
	*x = GovulncheckConfig{}
	mi := &file_proto_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovulncheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovulncheckConfig) ProtoMessage() {}

func (x *GovulncheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovulncheckConfig.ProtoReflect.Descriptor instead.
func (*GovulncheckConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{3}
}

func (x *GovulncheckConfig) GetOfflineVulnDbPath() string {
	if x != nil {
		return x.OfflineVulnDbPath
	}
	return ""
}

type ArchiveConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
}

func (x *ArchiveConfig) Reset() {
	*x = ArchiveConfig{}
	mi := &file_proto_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveConfig) ProtoMessage() {}

func (x *ArchiveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveConfig.ProtoReflect.Descriptor instead.
func (*ArchiveConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{4}
}

func (x *ArchiveConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type OVAConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
}

func (x *OVAConfig) Reset() {
	*x = OVAConfig{}
	mi := &file_proto_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OVAConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OVAConfig) ProtoMessage() {}

func (x *OVAConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OVAConfig.ProtoReflect.Descriptor instead.
func (*OVAConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{5}
}

func (x *OVAConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type VDIConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
}

func (x *VDIConfig) Reset() {
	*x = VDIConfig{}
	mi := &file_proto_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VDIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VDIConfig) ProtoMessage() {}

func (x *VDIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VDIConfig.ProtoReflect.Descriptor instead.
func (*VDIConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{6}
}

func (x *VDIConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type VMDKConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
}

func (x *VMDKConfig) Reset() {
	*x = VMDKConfig{}
	mi := &file_proto_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMDKConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMDKConfig) ProtoMessage() {}

func (x *VMDKConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMDKConfig.ProtoReflect.Descriptor instead.
func (*VMDKConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{7}
}

func (x *VMDKConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

var File_proto_config_proto protoreflect.FileDescriptor

var file_proto_config_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x22, 0x85, 0x01,
	0x0a, 0x0c, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2d,
	0x0a, 0x13, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6d, 0x61, 0x78,
	0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x46, 0x0a,
	0x0f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x72,
	0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x66, 0x69, 0x63, 0x22, 0xc7, 0x02, 0x0a, 0x14, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x36,
	0x0a, 0x09, 0x67, 0x6f, 0x5f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x2e, 0x47, 0x6f, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x08, 0x67, 0x6f,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x3e, 0x0a, 0x0b, 0x67, 0x6f, 0x76, 0x75, 0x6c, 0x6e,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x63,
	0x61, 0x6c, 0x69, 0x62, 0x72, 0x2e, 0x47, 0x6f, 0x76, 0x75, 0x6c, 0x6e, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x6f, 0x76, 0x75, 0x6c,
	0x6e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x32, 0x0a, 0x07, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x62,
	0x72, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48,
	0x00, 0x52, 0x07, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x6f, 0x76,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x62,
	0x72, 0x2e, 0x4f, 0x56, 0x41, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x03, 0x6f,
	0x76, 0x61, 0x12, 0x26, 0x0a, 0x03, 0x76, 0x64, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x2e, 0x56, 0x44, 0x49, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x03, 0x76, 0x64, 0x69, 0x12, 0x29, 0x0a, 0x04, 0x76, 0x6d,
	0x64, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x69,
	0x62, 0x72, 0x2e, 0x56, 0x4d, 0x44, 0x4b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52,
	0x04, 0x76, 0x6d, 0x64, 0x6b, 0x42, 0x08, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22,
	0x42, 0x0a, 0x0e, 0x47, 0x6f, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x30, 0x0a, 0x14, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x72, 0x6f,
	0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x12, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x44, 0x0a, 0x11, 0x47, 0x6f, 0x76, 0x75, 0x6c, 0x6e, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2f, 0x0a, 0x14, 0x6f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x76, 0x75, 0x6c, 0x6e, 0x5f, 0x64, 0x62, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x56,
	0x75, 0x6c, 0x6e, 0x44, 0x62, 0x50, 0x61, 0x74, 0x68, 0x22, 0x3e, 0x0a, 0x0d, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2d, 0x0a, 0x13, 0x6d, 0x61,
	0x78, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x09, 0x4f, 0x56, 0x41,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2d, 0x0a, 0x13, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x10, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x09, 0x56, 0x44, 0x49, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x2d, 0x0a, 0x13, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x10, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x22, 0x3b, 0x0a, 0x0a, 0x56, 0x4d, 0x44, 0x4b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x2d, 0x0a, 0x13, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6d, 0x61,
	0x78, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x42,
	0x42, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x01, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x73, 0x63,
	0x61, 0x6c, 0x69, 0x62, 0x72, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_config_proto_rawDescOnce sync.Once
	file_proto_config_proto_rawDescData = file_proto_config_proto_rawDesc
)

func file_proto_config_proto_rawDescGZIP() []byte {
	file_proto_config_proto_rawDescOnce.Do(func() {
		file_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_config_proto_rawDescData)
	})
	return file_proto_config_proto_rawDescData
}

var file_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_config_proto_goTypes = []any{
	(*PluginConfig)(nil),         // 0: scalibr.PluginConfig
	(*PluginSpecificConfig)(nil), // 1: scalibr.PluginSpecificConfig
	(*GoBinaryConfig)(nil),       // 2: scalibr.GoBinaryConfig
	(*GovulncheckConfig)(nil),    // 3: scalibr.GovulncheckConfig
	(*ArchiveConfig)(nil),        // 4: scalibr.ArchiveConfig
	(*OVAConfig)(nil),            // 5: scalibr.OVAConfig
	(*VDIConfig)(nil),            // 6: scalibr.VDIConfig
	(*VMDKConfig)(nil),           // 7: scalibr.VMDKConfig
}
var file_proto_config_proto_depIdxs = []int32{
	1, // 0: scalibr.PluginConfig.plugin_specific:type_name -> scalibr.PluginSpecificConfig
	2, // 1: scalibr.PluginSpecificConfig.go_binary:type_name -> scalibr.GoBinaryConfig
	3, // 2: scalibr.PluginSpecificConfig.govulncheck:type_name -> scalibr.GovulncheckConfig
	4, // 3: scalibr.PluginSpecificConfig.archive:type_name -> scalibr.ArchiveConfig
	5, // 4: scalibr.PluginSpecificConfig.ova:type_name -> scalibr.OVAConfig
	6, // 5: scalibr.PluginSpecificConfig.vdi:type_name -> scalibr.VDIConfig
	7, // 6: scalibr.PluginSpecificConfig.vmdk:type_name -> scalibr.VMDKConfig
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_config_proto_init() }
func file_proto_config_proto_init() {
	if File_proto_config_proto != nil {
		return
	}
	file_proto_config_proto_msgTypes[1].OneofWrappers = []any{
		(*PluginSpecificConfig_GoBinary)(nil),
		(*PluginSpecificConfig_Govulncheck)(nil),
		(*PluginSpecificConfig_Archive)(nil),
		(*PluginSpecificConfig_Ova)(nil),
		(*PluginSpecificConfig_Vdi)(nil),
		(*PluginSpecificConfig_Vmdk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_config_proto_goTypes,
		DependencyIndexes: file_proto_config_proto_depIdxs,
		MessageInfos:      file_proto_config_proto_msgTypes,
	}.Build()
	File_proto_config_proto = out.File
	file_proto_config_proto_rawDesc = nil
	file_proto_config_proto_goTypes = nil
	file_proto_config_proto_depIdxs = nil
}
