//
// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/config.proto

package config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	// The local directory to store the downloaded manifests during dependency
	// resolution.
	LocalRegistry string `protobuf:"bytes,3,opt,name=local_registry,json=localRegistry,proto3" json:"local_registry,omitempty"`
	// If true, do not try to create google.DefaultClient for Artifact Registry
	// during dependency resolution.
	DisableGoogleAuth bool `protobuf:"varint,4,opt,name=disable_google_auth,json=disableGoogleAuth,proto3" json:"disable_google_auth,omitempty"`
	// The user agent to use when making requests.
	UserAgent string `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// Config values that only apply to a single plugin.
	PluginSpecific []*PluginSpecificConfig `protobuf:"bytes,2,rep,name=plugin_specific,json=pluginSpecific,proto3" json:"plugin_specific,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PluginConfig) Reset() {
	*x = PluginConfig{}
	mi := &file_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginConfig) ProtoMessage() {}

func (x *PluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginConfig.ProtoReflect.Descriptor instead.
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *PluginConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

func (x *PluginConfig) GetLocalRegistry() string {
	if x != nil {
		return x.LocalRegistry
	}
	return ""
}

func (x *PluginConfig) GetDisableGoogleAuth() bool {
	if x != nil {
		return x.DisableGoogleAuth
	}
	return false
}

func (x *PluginConfig) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *PluginConfig) GetPluginSpecific() []*PluginSpecificConfig {
	if x != nil {
		return x.PluginSpecific
	}
	return nil
}

type PluginSpecificConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Config:
	//
	//	*PluginSpecificConfig_GoBinary
	//	*PluginSpecificConfig_Govulncheck
	//	*PluginSpecificConfig_Archive
	//	*PluginSpecificConfig_Ova
	//	*PluginSpecificConfig_Vdi
	//	*PluginSpecificConfig_Vmdk
	//	*PluginSpecificConfig_HashicorpVaultValidator
	//	*PluginSpecificConfig_SdpInspect
	//	*PluginSpecificConfig_PomXmlNet
	//	*PluginSpecificConfig_Chocolatey
	//	*PluginSpecificConfig_Dpkg
	//	*PluginSpecificConfig_Rpm
	//	*PluginSpecificConfig_Apk
	//	*PluginSpecificConfig_Cos
	//	*PluginSpecificConfig_Snap
	//	*PluginSpecificConfig_KernelModule
	//	*PluginSpecificConfig_Vmlinuz
	//	*PluginSpecificConfig_Pacman
	//	*PluginSpecificConfig_Portage
	//	*PluginSpecificConfig_Flatpak
	//	*PluginSpecificConfig_Macapps
	//	*PluginSpecificConfig_Podman
	//	*PluginSpecificConfig_DockerBaseImage
	//	*PluginSpecificConfig_Containerd
	//	*PluginSpecificConfig_DockerComposeImage
	//	*PluginSpecificConfig_K8SImage
	Config        isPluginSpecificConfig_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginSpecificConfig) Reset() {
	*x = PluginSpecificConfig{}
	mi := &file_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSpecificConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSpecificConfig) ProtoMessage() {}

func (x *PluginSpecificConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSpecificConfig.ProtoReflect.Descriptor instead.
func (*PluginSpecificConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *PluginSpecificConfig) GetConfig() isPluginSpecificConfig_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *PluginSpecificConfig) GetGoBinary() *GoBinaryConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_GoBinary); ok {
			return x.GoBinary
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetGovulncheck() *GovulncheckConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Govulncheck); ok {
			return x.Govulncheck
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetArchive() *ArchiveConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Archive); ok {
			return x.Archive
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetOva() *OVAConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Ova); ok {
			return x.Ova
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetVdi() *VDIConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Vdi); ok {
			return x.Vdi
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetVmdk() *VMDKConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Vmdk); ok {
			return x.Vmdk
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetHashicorpVaultValidator() *HashiCorpVaultValidatorConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_HashicorpVaultValidator); ok {
			return x.HashicorpVaultValidator
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetSdpInspect() *SDPInspectConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_SdpInspect); ok {
			return x.SdpInspect
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetPomXmlNet() *POMXMLNetConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_PomXmlNet); ok {
			return x.PomXmlNet
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetChocolatey() *ChocolateyConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Chocolatey); ok {
			return x.Chocolatey
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetDpkg() *DpkgConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Dpkg); ok {
			return x.Dpkg
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetRpm() *RpmConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Rpm); ok {
			return x.Rpm
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetApk() *ApkConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Apk); ok {
			return x.Apk
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetCos() *CosConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Cos); ok {
			return x.Cos
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetSnap() *SnapConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Snap); ok {
			return x.Snap
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetKernelModule() *KernelModuleConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_KernelModule); ok {
			return x.KernelModule
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetVmlinuz() *VmlinuzConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Vmlinuz); ok {
			return x.Vmlinuz
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetPacman() *PacmanConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Pacman); ok {
			return x.Pacman
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetPortage() *PortageConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Portage); ok {
			return x.Portage
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetFlatpak() *FlatpakConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Flatpak); ok {
			return x.Flatpak
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetMacapps() *MacAppsConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Macapps); ok {
			return x.Macapps
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetPodman() *PodmanConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Podman); ok {
			return x.Podman
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetDockerBaseImage() *DockerBaseImageConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_DockerBaseImage); ok {
			return x.DockerBaseImage
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetContainerd() *ContainerdConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Containerd); ok {
			return x.Containerd
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetDockerComposeImage() *DockerComposeImageConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_DockerComposeImage); ok {
			return x.DockerComposeImage
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetK8SImage() *K8SImageConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_K8SImage); ok {
			return x.K8SImage
		}
	}
	return nil
}

type isPluginSpecificConfig_Config interface {
	isPluginSpecificConfig_Config()
}

type PluginSpecificConfig_GoBinary struct {
	GoBinary *GoBinaryConfig `protobuf:"bytes,1,opt,name=go_binary,json=goBinary,proto3,oneof"`
}

type PluginSpecificConfig_Govulncheck struct {
	Govulncheck *GovulncheckConfig `protobuf:"bytes,2,opt,name=govulncheck,proto3,oneof"`
}

type PluginSpecificConfig_Archive struct {
	Archive *ArchiveConfig `protobuf:"bytes,3,opt,name=archive,proto3,oneof"`
}

type PluginSpecificConfig_Ova struct {
	Ova *OVAConfig `protobuf:"bytes,4,opt,name=ova,proto3,oneof"`
}

type PluginSpecificConfig_Vdi struct {
	Vdi *VDIConfig `protobuf:"bytes,5,opt,name=vdi,proto3,oneof"`
}

type PluginSpecificConfig_Vmdk struct {
	Vmdk *VMDKConfig `protobuf:"bytes,6,opt,name=vmdk,proto3,oneof"`
}

type PluginSpecificConfig_HashicorpVaultValidator struct {
	HashicorpVaultValidator *HashiCorpVaultValidatorConfig `protobuf:"bytes,7,opt,name=hashicorp_vault_validator,json=hashicorpVaultValidator,proto3,oneof"`
}

type PluginSpecificConfig_SdpInspect struct {
	SdpInspect *SDPInspectConfig `protobuf:"bytes,8,opt,name=sdp_inspect,json=sdpInspect,proto3,oneof"`
}

type PluginSpecificConfig_PomXmlNet struct {
	PomXmlNet *POMXMLNetConfig `protobuf:"bytes,9,opt,name=pom_xml_net,json=pomXmlNet,proto3,oneof"`
}

type PluginSpecificConfig_Chocolatey struct {
	Chocolatey *ChocolateyConfig `protobuf:"bytes,10,opt,name=chocolatey,proto3,oneof"`
}

type PluginSpecificConfig_Dpkg struct {
	Dpkg *DpkgConfig `protobuf:"bytes,11,opt,name=dpkg,proto3,oneof"`
}

type PluginSpecificConfig_Rpm struct {
	Rpm *RpmConfig `protobuf:"bytes,12,opt,name=rpm,proto3,oneof"`
}

type PluginSpecificConfig_Apk struct {
	Apk *ApkConfig `protobuf:"bytes,13,opt,name=apk,proto3,oneof"`
}

type PluginSpecificConfig_Cos struct {
	Cos *CosConfig `protobuf:"bytes,14,opt,name=cos,proto3,oneof"`
}

type PluginSpecificConfig_Snap struct {
	Snap *SnapConfig `protobuf:"bytes,15,opt,name=snap,proto3,oneof"`
}

type PluginSpecificConfig_KernelModule struct {
	KernelModule *KernelModuleConfig `protobuf:"bytes,16,opt,name=kernel_module,json=kernelModule,proto3,oneof"`
}

type PluginSpecificConfig_Vmlinuz struct {
	Vmlinuz *VmlinuzConfig `protobuf:"bytes,17,opt,name=vmlinuz,proto3,oneof"`
}

type PluginSpecificConfig_Pacman struct {
	Pacman *PacmanConfig `protobuf:"bytes,18,opt,name=pacman,proto3,oneof"`
}

type PluginSpecificConfig_Portage struct {
	Portage *PortageConfig `protobuf:"bytes,19,opt,name=portage,proto3,oneof"`
}

type PluginSpecificConfig_Flatpak struct {
	Flatpak *FlatpakConfig `protobuf:"bytes,20,opt,name=flatpak,proto3,oneof"`
}

type PluginSpecificConfig_Macapps struct {
	Macapps *MacAppsConfig `protobuf:"bytes,21,opt,name=macapps,proto3,oneof"`
}

type PluginSpecificConfig_Podman struct {
	Podman *PodmanConfig `protobuf:"bytes,22,opt,name=podman,proto3,oneof"`
}

type PluginSpecificConfig_DockerBaseImage struct {
	DockerBaseImage *DockerBaseImageConfig `protobuf:"bytes,23,opt,name=docker_base_image,json=dockerBaseImage,proto3,oneof"`
}

type PluginSpecificConfig_Containerd struct {
	Containerd *ContainerdConfig `protobuf:"bytes,24,opt,name=containerd,proto3,oneof"`
}

type PluginSpecificConfig_DockerComposeImage struct {
	DockerComposeImage *DockerComposeImageConfig `protobuf:"bytes,25,opt,name=docker_compose_image,json=dockerComposeImage,proto3,oneof"`
}

type PluginSpecificConfig_K8SImage struct {
	K8SImage *K8SImageConfig `protobuf:"bytes,26,opt,name=k8s_image,json=k8sImage,proto3,oneof"`
}

func (*PluginSpecificConfig_GoBinary) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Govulncheck) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Archive) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Ova) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Vdi) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Vmdk) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_HashicorpVaultValidator) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_SdpInspect) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_PomXmlNet) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Chocolatey) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Dpkg) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Rpm) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Apk) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Cos) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Snap) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_KernelModule) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Vmlinuz) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Pacman) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Portage) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Flatpak) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Macapps) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Podman) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_DockerBaseImage) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Containerd) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_DockerComposeImage) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_K8SImage) isPluginSpecificConfig_Config() {}

type GoBinaryConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enables extracting the module version from the Go binary content.
	VersionFromContent bool `protobuf:"varint,1,opt,name=version_from_content,json=versionFromContent,proto3" json:"version_from_content,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GoBinaryConfig) Reset() {
	*x = GoBinaryConfig{}
	mi := &file_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoBinaryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoBinaryConfig) ProtoMessage() {}

func (x *GoBinaryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoBinaryConfig.ProtoReflect.Descriptor instead.
func (*GoBinaryConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{2}
}

func (x *GoBinaryConfig) GetVersionFromContent() bool {
	if x != nil {
		return x.VersionFromContent
	}
	return false
}

type GovulncheckConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to the offline vuln DB to pass to govunlcheck. If empty,
	// the detector will query vulns from the net instead.
	OfflineVulnDbPath string `protobuf:"bytes,1,opt,name=offline_vuln_db_path,json=offlineVulnDbPath,proto3" json:"offline_vuln_db_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GovulncheckConfig) Reset() {
	*x = GovulncheckConfig{}
	mi := &file_proto_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovulncheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovulncheckConfig) ProtoMessage() {}

func (x *GovulncheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovulncheckConfig.ProtoReflect.Descriptor instead.
func (*GovulncheckConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{3}
}

func (x *GovulncheckConfig) GetOfflineVulnDbPath() string {
	if x != nil {
		return x.OfflineVulnDbPath
	}
	return ""
}

type ArchiveConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ArchiveConfig) Reset() {
	*x = ArchiveConfig{}
	mi := &file_proto_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveConfig) ProtoMessage() {}

func (x *ArchiveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveConfig.ProtoReflect.Descriptor instead.
func (*ArchiveConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{4}
}

func (x *ArchiveConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type OVAConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OVAConfig) Reset() {
	*x = OVAConfig{}
	mi := &file_proto_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OVAConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OVAConfig) ProtoMessage() {}

func (x *OVAConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OVAConfig.ProtoReflect.Descriptor instead.
func (*OVAConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{5}
}

func (x *OVAConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type VDIConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VDIConfig) Reset() {
	*x = VDIConfig{}
	mi := &file_proto_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VDIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VDIConfig) ProtoMessage() {}

func (x *VDIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VDIConfig.ProtoReflect.Descriptor instead.
func (*VDIConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{6}
}

func (x *VDIConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type VMDKConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VMDKConfig) Reset() {
	*x = VMDKConfig{}
	mi := &file_proto_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMDKConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMDKConfig) ProtoMessage() {}

func (x *VMDKConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMDKConfig.ProtoReflect.Descriptor instead.
func (*VMDKConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{7}
}

func (x *VMDKConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type ChocolateyConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChocolateyConfig) Reset() {
	*x = ChocolateyConfig{}
	mi := &file_proto_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChocolateyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChocolateyConfig) ProtoMessage() {}

func (x *ChocolateyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChocolateyConfig.ProtoReflect.Descriptor instead.
func (*ChocolateyConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{8}
}

func (x *ChocolateyConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type HashiCorpVaultValidatorConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL of the Vault server to connect to.
	// https://developer.hashicorp.com/vault
	VaultUrl      string `protobuf:"bytes,1,opt,name=vault_url,json=vaultUrl,proto3" json:"vault_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashiCorpVaultValidatorConfig) Reset() {
	*x = HashiCorpVaultValidatorConfig{}
	mi := &file_proto_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashiCorpVaultValidatorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashiCorpVaultValidatorConfig) ProtoMessage() {}

func (x *HashiCorpVaultValidatorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashiCorpVaultValidatorConfig.ProtoReflect.Descriptor instead.
func (*HashiCorpVaultValidatorConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{9}
}

func (x *HashiCorpVaultValidatorConfig) GetVaultUrl() string {
	if x != nil {
		return x.VaultUrl
	}
	return ""
}

type SDPInspectConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The GCP project id to use for Sensitive Data Protection InspectContent API
	// calls.
	ProjectId     string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SDPInspectConfig) Reset() {
	*x = SDPInspectConfig{}
	mi := &file_proto_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SDPInspectConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDPInspectConfig) ProtoMessage() {}

func (x *SDPInspectConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDPInspectConfig.ProtoReflect.Descriptor instead.
func (*SDPInspectConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{10}
}

func (x *SDPInspectConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type POMXMLNetConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL of the upstream Maven registry.
	UpstreamRegistry string `protobuf:"bytes,1,opt,name=upstream_registry,json=upstreamRegistry,proto3" json:"upstream_registry,omitempty"`
	// If true, use deps.dev requirements API for dependency resolution.
	DepsDevRequirements bool `protobuf:"varint,2,opt,name=deps_dev_requirements,json=depsDevRequirements,proto3" json:"deps_dev_requirements,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *POMXMLNetConfig) Reset() {
	*x = POMXMLNetConfig{}
	mi := &file_proto_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *POMXMLNetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POMXMLNetConfig) ProtoMessage() {}

func (x *POMXMLNetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POMXMLNetConfig.ProtoReflect.Descriptor instead.
func (*POMXMLNetConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{11}
}

func (x *POMXMLNetConfig) GetUpstreamRegistry() string {
	if x != nil {
		return x.UpstreamRegistry
	}
	return ""
}

func (x *POMXMLNetConfig) GetDepsDevRequirements() bool {
	if x != nil {
		return x.DepsDevRequirements
	}
	return false
}

type DpkgConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IncludeNotInstalled includes packages that are not installed
	// (e.g. `deinstall`, `purge`, and those missing a status field).
	IncludeNotInstalled bool `protobuf:"varint,1,opt,name=include_not_installed,json=includeNotInstalled,proto3" json:"include_not_installed,omitempty"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,2,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DpkgConfig) Reset() {
	*x = DpkgConfig{}
	mi := &file_proto_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DpkgConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DpkgConfig) ProtoMessage() {}

func (x *DpkgConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DpkgConfig.ProtoReflect.Descriptor instead.
func (*DpkgConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{12}
}

func (x *DpkgConfig) GetIncludeNotInstalled() bool {
	if x != nil {
		return x.IncludeNotInstalled
	}
	return false
}

func (x *DpkgConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type RpmConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timeout in seconds for parsing the RPM database.
	TimeoutSeconds int64 `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,2,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RpmConfig) Reset() {
	*x = RpmConfig{}
	mi := &file_proto_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpmConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpmConfig) ProtoMessage() {}

func (x *RpmConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpmConfig.ProtoReflect.Descriptor instead.
func (*RpmConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{13}
}

func (x *RpmConfig) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *RpmConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type ApkConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApkConfig) Reset() {
	*x = ApkConfig{}
	mi := &file_proto_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkConfig) ProtoMessage() {}

func (x *ApkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkConfig.ProtoReflect.Descriptor instead.
func (*ApkConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{14}
}

func (x *ApkConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type CosConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CosConfig) Reset() {
	*x = CosConfig{}
	mi := &file_proto_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosConfig) ProtoMessage() {}

func (x *CosConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosConfig.ProtoReflect.Descriptor instead.
func (*CosConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{15}
}

func (x *CosConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type SnapConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SnapConfig) Reset() {
	*x = SnapConfig{}
	mi := &file_proto_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapConfig) ProtoMessage() {}

func (x *SnapConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapConfig.ProtoReflect.Descriptor instead.
func (*SnapConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{16}
}

func (x *SnapConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type KernelModuleConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KernelModuleConfig) Reset() {
	*x = KernelModuleConfig{}
	mi := &file_proto_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelModuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelModuleConfig) ProtoMessage() {}

func (x *KernelModuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelModuleConfig.ProtoReflect.Descriptor instead.
func (*KernelModuleConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{17}
}

func (x *KernelModuleConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type VmlinuzConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VmlinuzConfig) Reset() {
	*x = VmlinuzConfig{}
	mi := &file_proto_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmlinuzConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmlinuzConfig) ProtoMessage() {}

func (x *VmlinuzConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmlinuzConfig.ProtoReflect.Descriptor instead.
func (*VmlinuzConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{18}
}

func (x *VmlinuzConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type PacmanConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PacmanConfig) Reset() {
	*x = PacmanConfig{}
	mi := &file_proto_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacmanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacmanConfig) ProtoMessage() {}

func (x *PacmanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacmanConfig.ProtoReflect.Descriptor instead.
func (*PacmanConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{19}
}

func (x *PacmanConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type PortageConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PortageConfig) Reset() {
	*x = PortageConfig{}
	mi := &file_proto_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortageConfig) ProtoMessage() {}

func (x *PortageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortageConfig.ProtoReflect.Descriptor instead.
func (*PortageConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{20}
}

func (x *PortageConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type FlatpakConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FlatpakConfig) Reset() {
	*x = FlatpakConfig{}
	mi := &file_proto_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatpakConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatpakConfig) ProtoMessage() {}

func (x *FlatpakConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatpakConfig.ProtoReflect.Descriptor instead.
func (*FlatpakConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{21}
}

func (x *FlatpakConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type MacAppsConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MacAppsConfig) Reset() {
	*x = MacAppsConfig{}
	mi := &file_proto_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MacAppsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MacAppsConfig) ProtoMessage() {}

func (x *MacAppsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MacAppsConfig.ProtoReflect.Descriptor instead.
func (*MacAppsConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{22}
}

func (x *MacAppsConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type PodmanConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IncludeStopped specifies whether to list all containers, including those
	// that are not currently running.
	IncludeStopped bool `protobuf:"varint,1,opt,name=include_stopped,json=includeStopped,proto3" json:"include_stopped,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PodmanConfig) Reset() {
	*x = PodmanConfig{}
	mi := &file_proto_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodmanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodmanConfig) ProtoMessage() {}

func (x *PodmanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodmanConfig.ProtoReflect.Descriptor instead.
func (*PodmanConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{23}
}

func (x *PodmanConfig) GetIncludeStopped() bool {
	if x != nil {
		return x.IncludeStopped
	}
	return false
}

type DockerBaseImageConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DockerBaseImageConfig) Reset() {
	*x = DockerBaseImageConfig{}
	mi := &file_proto_config_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerBaseImageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerBaseImageConfig) ProtoMessage() {}

func (x *DockerBaseImageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerBaseImageConfig.ProtoReflect.Descriptor instead.
func (*DockerBaseImageConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{24}
}

func (x *DockerBaseImageConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type ContainerdConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContainerdConfig) Reset() {
	*x = ContainerdConfig{}
	mi := &file_proto_config_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerdConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerdConfig) ProtoMessage() {}

func (x *ContainerdConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerdConfig.ProtoReflect.Descriptor instead.
func (*ContainerdConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{25}
}

func (x *ContainerdConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type DockerComposeImageConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DockerComposeImageConfig) Reset() {
	*x = DockerComposeImageConfig{}
	mi := &file_proto_config_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerComposeImageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerComposeImageConfig) ProtoMessage() {}

func (x *DockerComposeImageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerComposeImageConfig.ProtoReflect.Descriptor instead.
func (*DockerComposeImageConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{26}
}

func (x *DockerComposeImageConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type K8SImageConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *K8SImageConfig) Reset() {
	*x = K8SImageConfig{}
	mi := &file_proto_config_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SImageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SImageConfig) ProtoMessage() {}

func (x *K8SImageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SImageConfig.ProtoReflect.Descriptor instead.
func (*K8SImageConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{27}
}

func (x *K8SImageConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

var File_proto_config_proto protoreflect.FileDescriptor

const file_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x12proto/config.proto\x12\ascalibr\"\xfb\x01\n" +
	"\fPluginConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\x12%\n" +
	"\x0elocal_registry\x18\x03 \x01(\tR\rlocalRegistry\x12.\n" +
	"\x13disable_google_auth\x18\x04 \x01(\bR\x11disableGoogleAuth\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12F\n" +
	"\x0fplugin_specific\x18\x02 \x03(\v2\x1d.scalibr.PluginSpecificConfigR\x0epluginSpecific\"\xc2\v\n" +
	"\x14PluginSpecificConfig\x126\n" +
	"\tgo_binary\x18\x01 \x01(\v2\x17.scalibr.GoBinaryConfigH\x00R\bgoBinary\x12>\n" +
	"\vgovulncheck\x18\x02 \x01(\v2\x1a.scalibr.GovulncheckConfigH\x00R\vgovulncheck\x122\n" +
	"\aarchive\x18\x03 \x01(\v2\x16.scalibr.ArchiveConfigH\x00R\aarchive\x12&\n" +
	"\x03ova\x18\x04 \x01(\v2\x12.scalibr.OVAConfigH\x00R\x03ova\x12&\n" +
	"\x03vdi\x18\x05 \x01(\v2\x12.scalibr.VDIConfigH\x00R\x03vdi\x12)\n" +
	"\x04vmdk\x18\x06 \x01(\v2\x13.scalibr.VMDKConfigH\x00R\x04vmdk\x12d\n" +
	"\x19hashicorp_vault_validator\x18\a \x01(\v2&.scalibr.HashiCorpVaultValidatorConfigH\x00R\x17hashicorpVaultValidator\x12<\n" +
	"\vsdp_inspect\x18\b \x01(\v2\x19.scalibr.SDPInspectConfigH\x00R\n" +
	"sdpInspect\x12:\n" +
	"\vpom_xml_net\x18\t \x01(\v2\x18.scalibr.POMXMLNetConfigH\x00R\tpomXmlNet\x12;\n" +
	"\n" +
	"chocolatey\x18\n" +
	" \x01(\v2\x19.scalibr.ChocolateyConfigH\x00R\n" +
	"chocolatey\x12)\n" +
	"\x04dpkg\x18\v \x01(\v2\x13.scalibr.DpkgConfigH\x00R\x04dpkg\x12&\n" +
	"\x03rpm\x18\f \x01(\v2\x12.scalibr.RpmConfigH\x00R\x03rpm\x12&\n" +
	"\x03apk\x18\r \x01(\v2\x12.scalibr.ApkConfigH\x00R\x03apk\x12&\n" +
	"\x03cos\x18\x0e \x01(\v2\x12.scalibr.CosConfigH\x00R\x03cos\x12)\n" +
	"\x04snap\x18\x0f \x01(\v2\x13.scalibr.SnapConfigH\x00R\x04snap\x12B\n" +
	"\rkernel_module\x18\x10 \x01(\v2\x1b.scalibr.KernelModuleConfigH\x00R\fkernelModule\x122\n" +
	"\avmlinuz\x18\x11 \x01(\v2\x16.scalibr.VmlinuzConfigH\x00R\avmlinuz\x12/\n" +
	"\x06pacman\x18\x12 \x01(\v2\x15.scalibr.PacmanConfigH\x00R\x06pacman\x122\n" +
	"\aportage\x18\x13 \x01(\v2\x16.scalibr.PortageConfigH\x00R\aportage\x122\n" +
	"\aflatpak\x18\x14 \x01(\v2\x16.scalibr.FlatpakConfigH\x00R\aflatpak\x122\n" +
	"\amacapps\x18\x15 \x01(\v2\x16.scalibr.MacAppsConfigH\x00R\amacapps\x12/\n" +
	"\x06podman\x18\x16 \x01(\v2\x15.scalibr.PodmanConfigH\x00R\x06podman\x12L\n" +
	"\x11docker_base_image\x18\x17 \x01(\v2\x1e.scalibr.DockerBaseImageConfigH\x00R\x0fdockerBaseImage\x12;\n" +
	"\n" +
	"containerd\x18\x18 \x01(\v2\x19.scalibr.ContainerdConfigH\x00R\n" +
	"containerd\x12U\n" +
	"\x14docker_compose_image\x18\x19 \x01(\v2!.scalibr.DockerComposeImageConfigH\x00R\x12dockerComposeImage\x126\n" +
	"\tk8s_image\x18\x1a \x01(\v2\x17.scalibr.K8sImageConfigH\x00R\bk8sImageB\b\n" +
	"\x06config\"B\n" +
	"\x0eGoBinaryConfig\x120\n" +
	"\x14version_from_content\x18\x01 \x01(\bR\x12versionFromContent\"D\n" +
	"\x11GovulncheckConfig\x12/\n" +
	"\x14offline_vuln_db_path\x18\x01 \x01(\tR\x11offlineVulnDbPath\">\n" +
	"\rArchiveConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\":\n" +
	"\tOVAConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\":\n" +
	"\tVDIConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\";\n" +
	"\n" +
	"VMDKConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\"A\n" +
	"\x10ChocolateyConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\"<\n" +
	"\x1dHashiCorpVaultValidatorConfig\x12\x1b\n" +
	"\tvault_url\x18\x01 \x01(\tR\bvaultUrl\"1\n" +
	"\x10SDPInspectConfig\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"r\n" +
	"\x0fPOMXMLNetConfig\x12+\n" +
	"\x11upstream_registry\x18\x01 \x01(\tR\x10upstreamRegistry\x122\n" +
	"\x15deps_dev_requirements\x18\x02 \x01(\bR\x13depsDevRequirements\"o\n" +
	"\n" +
	"DpkgConfig\x122\n" +
	"\x15include_not_installed\x18\x01 \x01(\bR\x13includeNotInstalled\x12-\n" +
	"\x13max_file_size_bytes\x18\x02 \x01(\x03R\x10maxFileSizeBytes\"c\n" +
	"\tRpmConfig\x12'\n" +
	"\x0ftimeout_seconds\x18\x01 \x01(\x03R\x0etimeoutSeconds\x12-\n" +
	"\x13max_file_size_bytes\x18\x02 \x01(\x03R\x10maxFileSizeBytes\":\n" +
	"\tApkConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\":\n" +
	"\tCosConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\";\n" +
	"\n" +
	"SnapConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\"C\n" +
	"\x12KernelModuleConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\">\n" +
	"\rVmlinuzConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\"=\n" +
	"\fPacmanConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\">\n" +
	"\rPortageConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\">\n" +
	"\rFlatpakConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\">\n" +
	"\rMacAppsConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\"7\n" +
	"\fPodmanConfig\x12'\n" +
	"\x0finclude_stopped\x18\x01 \x01(\bR\x0eincludeStopped\"F\n" +
	"\x15DockerBaseImageConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\"A\n" +
	"\x10ContainerdConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\"I\n" +
	"\x18DockerComposeImageConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\"?\n" +
	"\x0eK8sImageConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytesBFB\x06ConfigP\x01Z:github.com/google/osv-scalibr/binary/proto/config_go_protob\x06proto3"

var (
	file_proto_config_proto_rawDescOnce sync.Once
	file_proto_config_proto_rawDescData []byte
)

func file_proto_config_proto_rawDescGZIP() []byte {
	file_proto_config_proto_rawDescOnce.Do(func() {
		file_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)))
	})
	return file_proto_config_proto_rawDescData
}

var file_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_config_proto_goTypes = []any{
	(*PluginConfig)(nil),                  // 0: scalibr.PluginConfig
	(*PluginSpecificConfig)(nil),          // 1: scalibr.PluginSpecificConfig
	(*GoBinaryConfig)(nil),                // 2: scalibr.GoBinaryConfig
	(*GovulncheckConfig)(nil),             // 3: scalibr.GovulncheckConfig
	(*ArchiveConfig)(nil),                 // 4: scalibr.ArchiveConfig
	(*OVAConfig)(nil),                     // 5: scalibr.OVAConfig
	(*VDIConfig)(nil),                     // 6: scalibr.VDIConfig
	(*VMDKConfig)(nil),                    // 7: scalibr.VMDKConfig
	(*ChocolateyConfig)(nil),              // 8: scalibr.ChocolateyConfig
	(*HashiCorpVaultValidatorConfig)(nil), // 9: scalibr.HashiCorpVaultValidatorConfig
	(*SDPInspectConfig)(nil),              // 10: scalibr.SDPInspectConfig
	(*POMXMLNetConfig)(nil),               // 11: scalibr.POMXMLNetConfig
	(*DpkgConfig)(nil),                    // 12: scalibr.DpkgConfig
	(*RpmConfig)(nil),                     // 13: scalibr.RpmConfig
	(*ApkConfig)(nil),                     // 14: scalibr.ApkConfig
	(*CosConfig)(nil),                     // 15: scalibr.CosConfig
	(*SnapConfig)(nil),                    // 16: scalibr.SnapConfig
	(*KernelModuleConfig)(nil),            // 17: scalibr.KernelModuleConfig
	(*VmlinuzConfig)(nil),                 // 18: scalibr.VmlinuzConfig
	(*PacmanConfig)(nil),                  // 19: scalibr.PacmanConfig
	(*PortageConfig)(nil),                 // 20: scalibr.PortageConfig
	(*FlatpakConfig)(nil),                 // 21: scalibr.FlatpakConfig
	(*MacAppsConfig)(nil),                 // 22: scalibr.MacAppsConfig
	(*PodmanConfig)(nil),                  // 23: scalibr.PodmanConfig
	(*DockerBaseImageConfig)(nil),         // 24: scalibr.DockerBaseImageConfig
	(*ContainerdConfig)(nil),              // 25: scalibr.ContainerdConfig
	(*DockerComposeImageConfig)(nil),      // 26: scalibr.DockerComposeImageConfig
	(*K8SImageConfig)(nil),                // 27: scalibr.K8sImageConfig
}
var file_proto_config_proto_depIdxs = []int32{
	1,  // 0: scalibr.PluginConfig.plugin_specific:type_name -> scalibr.PluginSpecificConfig
	2,  // 1: scalibr.PluginSpecificConfig.go_binary:type_name -> scalibr.GoBinaryConfig
	3,  // 2: scalibr.PluginSpecificConfig.govulncheck:type_name -> scalibr.GovulncheckConfig
	4,  // 3: scalibr.PluginSpecificConfig.archive:type_name -> scalibr.ArchiveConfig
	5,  // 4: scalibr.PluginSpecificConfig.ova:type_name -> scalibr.OVAConfig
	6,  // 5: scalibr.PluginSpecificConfig.vdi:type_name -> scalibr.VDIConfig
	7,  // 6: scalibr.PluginSpecificConfig.vmdk:type_name -> scalibr.VMDKConfig
	9,  // 7: scalibr.PluginSpecificConfig.hashicorp_vault_validator:type_name -> scalibr.HashiCorpVaultValidatorConfig
	10, // 8: scalibr.PluginSpecificConfig.sdp_inspect:type_name -> scalibr.SDPInspectConfig
	11, // 9: scalibr.PluginSpecificConfig.pom_xml_net:type_name -> scalibr.POMXMLNetConfig
	8,  // 10: scalibr.PluginSpecificConfig.chocolatey:type_name -> scalibr.ChocolateyConfig
	12, // 11: scalibr.PluginSpecificConfig.dpkg:type_name -> scalibr.DpkgConfig
	13, // 12: scalibr.PluginSpecificConfig.rpm:type_name -> scalibr.RpmConfig
	14, // 13: scalibr.PluginSpecificConfig.apk:type_name -> scalibr.ApkConfig
	15, // 14: scalibr.PluginSpecificConfig.cos:type_name -> scalibr.CosConfig
	16, // 15: scalibr.PluginSpecificConfig.snap:type_name -> scalibr.SnapConfig
	17, // 16: scalibr.PluginSpecificConfig.kernel_module:type_name -> scalibr.KernelModuleConfig
	18, // 17: scalibr.PluginSpecificConfig.vmlinuz:type_name -> scalibr.VmlinuzConfig
	19, // 18: scalibr.PluginSpecificConfig.pacman:type_name -> scalibr.PacmanConfig
	20, // 19: scalibr.PluginSpecificConfig.portage:type_name -> scalibr.PortageConfig
	21, // 20: scalibr.PluginSpecificConfig.flatpak:type_name -> scalibr.FlatpakConfig
	22, // 21: scalibr.PluginSpecificConfig.macapps:type_name -> scalibr.MacAppsConfig
	23, // 22: scalibr.PluginSpecificConfig.podman:type_name -> scalibr.PodmanConfig
	24, // 23: scalibr.PluginSpecificConfig.docker_base_image:type_name -> scalibr.DockerBaseImageConfig
	25, // 24: scalibr.PluginSpecificConfig.containerd:type_name -> scalibr.ContainerdConfig
	26, // 25: scalibr.PluginSpecificConfig.docker_compose_image:type_name -> scalibr.DockerComposeImageConfig
	27, // 26: scalibr.PluginSpecificConfig.k8s_image:type_name -> scalibr.K8sImageConfig
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_proto_config_proto_init() }
func file_proto_config_proto_init() {
	if File_proto_config_proto != nil {
		return
	}
	file_proto_config_proto_msgTypes[1].OneofWrappers = []any{
		(*PluginSpecificConfig_GoBinary)(nil),
		(*PluginSpecificConfig_Govulncheck)(nil),
		(*PluginSpecificConfig_Archive)(nil),
		(*PluginSpecificConfig_Ova)(nil),
		(*PluginSpecificConfig_Vdi)(nil),
		(*PluginSpecificConfig_Vmdk)(nil),
		(*PluginSpecificConfig_HashicorpVaultValidator)(nil),
		(*PluginSpecificConfig_SdpInspect)(nil),
		(*PluginSpecificConfig_PomXmlNet)(nil),
		(*PluginSpecificConfig_Chocolatey)(nil),
		(*PluginSpecificConfig_Dpkg)(nil),
		(*PluginSpecificConfig_Rpm)(nil),
		(*PluginSpecificConfig_Apk)(nil),
		(*PluginSpecificConfig_Cos)(nil),
		(*PluginSpecificConfig_Snap)(nil),
		(*PluginSpecificConfig_KernelModule)(nil),
		(*PluginSpecificConfig_Vmlinuz)(nil),
		(*PluginSpecificConfig_Pacman)(nil),
		(*PluginSpecificConfig_Portage)(nil),
		(*PluginSpecificConfig_Flatpak)(nil),
		(*PluginSpecificConfig_Macapps)(nil),
		(*PluginSpecificConfig_Podman)(nil),
		(*PluginSpecificConfig_DockerBaseImage)(nil),
		(*PluginSpecificConfig_Containerd)(nil),
		(*PluginSpecificConfig_DockerComposeImage)(nil),
		(*PluginSpecificConfig_K8SImage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_config_proto_goTypes,
		DependencyIndexes: file_proto_config_proto_depIdxs,
		MessageInfos:      file_proto_config_proto_msgTypes,
	}.Build()
	File_proto_config_proto = out.File
	file_proto_config_proto_goTypes = nil
	file_proto_config_proto_depIdxs = nil
}
