//
// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/config.proto

package config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	// The local directory to store the downloaded manifests during dependency
	// resolution.
	LocalRegistry string `protobuf:"bytes,3,opt,name=local_registry,json=localRegistry,proto3" json:"local_registry,omitempty"`
	// If true, do not try to create google.DefaultClient for Artifact Registry
	// during dependency resolution.
	DisableGoogleAuth bool `protobuf:"varint,4,opt,name=disable_google_auth,json=disableGoogleAuth,proto3" json:"disable_google_auth,omitempty"`
	// Config values that only apply to a single plugin.
	PluginSpecific []*PluginSpecificConfig `protobuf:"bytes,2,rep,name=plugin_specific,json=pluginSpecific,proto3" json:"plugin_specific,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PluginConfig) Reset() {
	*x = PluginConfig{}
	mi := &file_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginConfig) ProtoMessage() {}

func (x *PluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginConfig.ProtoReflect.Descriptor instead.
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *PluginConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

func (x *PluginConfig) GetLocalRegistry() string {
	if x != nil {
		return x.LocalRegistry
	}
	return ""
}

func (x *PluginConfig) GetDisableGoogleAuth() bool {
	if x != nil {
		return x.DisableGoogleAuth
	}
	return false
}

func (x *PluginConfig) GetPluginSpecific() []*PluginSpecificConfig {
	if x != nil {
		return x.PluginSpecific
	}
	return nil
}

type PluginSpecificConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Config:
	//
	//	*PluginSpecificConfig_GoBinary
	//	*PluginSpecificConfig_Govulncheck
	//	*PluginSpecificConfig_Archive
	//	*PluginSpecificConfig_Ova
	//	*PluginSpecificConfig_Vdi
	//	*PluginSpecificConfig_Vmdk
	//	*PluginSpecificConfig_HashicorpVaultValidator
	//	*PluginSpecificConfig_SdpInspect
	//	*PluginSpecificConfig_PomXmlNet
	Config        isPluginSpecificConfig_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginSpecificConfig) Reset() {
	*x = PluginSpecificConfig{}
	mi := &file_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSpecificConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSpecificConfig) ProtoMessage() {}

func (x *PluginSpecificConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSpecificConfig.ProtoReflect.Descriptor instead.
func (*PluginSpecificConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *PluginSpecificConfig) GetConfig() isPluginSpecificConfig_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *PluginSpecificConfig) GetGoBinary() *GoBinaryConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_GoBinary); ok {
			return x.GoBinary
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetGovulncheck() *GovulncheckConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Govulncheck); ok {
			return x.Govulncheck
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetArchive() *ArchiveConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Archive); ok {
			return x.Archive
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetOva() *OVAConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Ova); ok {
			return x.Ova
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetVdi() *VDIConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Vdi); ok {
			return x.Vdi
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetVmdk() *VMDKConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_Vmdk); ok {
			return x.Vmdk
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetHashicorpVaultValidator() *HashiCorpVaultValidatorConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_HashicorpVaultValidator); ok {
			return x.HashicorpVaultValidator
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetSdpInspect() *SDPInspectConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_SdpInspect); ok {
			return x.SdpInspect
		}
	}
	return nil
}

func (x *PluginSpecificConfig) GetPomXmlNet() *POMXMLNetConfig {
	if x != nil {
		if x, ok := x.Config.(*PluginSpecificConfig_PomXmlNet); ok {
			return x.PomXmlNet
		}
	}
	return nil
}

type isPluginSpecificConfig_Config interface {
	isPluginSpecificConfig_Config()
}

type PluginSpecificConfig_GoBinary struct {
	GoBinary *GoBinaryConfig `protobuf:"bytes,1,opt,name=go_binary,json=goBinary,proto3,oneof"`
}

type PluginSpecificConfig_Govulncheck struct {
	Govulncheck *GovulncheckConfig `protobuf:"bytes,2,opt,name=govulncheck,proto3,oneof"`
}

type PluginSpecificConfig_Archive struct {
	Archive *ArchiveConfig `protobuf:"bytes,3,opt,name=archive,proto3,oneof"`
}

type PluginSpecificConfig_Ova struct {
	Ova *OVAConfig `protobuf:"bytes,4,opt,name=ova,proto3,oneof"`
}

type PluginSpecificConfig_Vdi struct {
	Vdi *VDIConfig `protobuf:"bytes,5,opt,name=vdi,proto3,oneof"`
}

type PluginSpecificConfig_Vmdk struct {
	Vmdk *VMDKConfig `protobuf:"bytes,6,opt,name=vmdk,proto3,oneof"`
}

type PluginSpecificConfig_HashicorpVaultValidator struct {
	HashicorpVaultValidator *HashiCorpVaultValidatorConfig `protobuf:"bytes,7,opt,name=hashicorp_vault_validator,json=hashicorpVaultValidator,proto3,oneof"`
}

type PluginSpecificConfig_SdpInspect struct {
	SdpInspect *SDPInspectConfig `protobuf:"bytes,8,opt,name=sdp_inspect,json=sdpInspect,proto3,oneof"`
}

type PluginSpecificConfig_PomXmlNet struct {
	PomXmlNet *POMXMLNetConfig `protobuf:"bytes,9,opt,name=pom_xml_net,json=pomXmlNet,proto3,oneof"`
}

func (*PluginSpecificConfig_GoBinary) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Govulncheck) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Archive) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Ova) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Vdi) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_Vmdk) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_HashicorpVaultValidator) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_SdpInspect) isPluginSpecificConfig_Config() {}

func (*PluginSpecificConfig_PomXmlNet) isPluginSpecificConfig_Config() {}

type GoBinaryConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enables extracting the module version from the Go binary content.
	VersionFromContent bool `protobuf:"varint,1,opt,name=version_from_content,json=versionFromContent,proto3" json:"version_from_content,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GoBinaryConfig) Reset() {
	*x = GoBinaryConfig{}
	mi := &file_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoBinaryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoBinaryConfig) ProtoMessage() {}

func (x *GoBinaryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoBinaryConfig.ProtoReflect.Descriptor instead.
func (*GoBinaryConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{2}
}

func (x *GoBinaryConfig) GetVersionFromContent() bool {
	if x != nil {
		return x.VersionFromContent
	}
	return false
}

type GovulncheckConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to the offline vuln DB to pass to govunlcheck. If empty,
	// the detector will query vulns from the net instead.
	OfflineVulnDbPath string `protobuf:"bytes,1,opt,name=offline_vuln_db_path,json=offlineVulnDbPath,proto3" json:"offline_vuln_db_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GovulncheckConfig) Reset() {
	*x = GovulncheckConfig{}
	mi := &file_proto_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovulncheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovulncheckConfig) ProtoMessage() {}

func (x *GovulncheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovulncheckConfig.ProtoReflect.Descriptor instead.
func (*GovulncheckConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{3}
}

func (x *GovulncheckConfig) GetOfflineVulnDbPath() string {
	if x != nil {
		return x.OfflineVulnDbPath
	}
	return ""
}

type ArchiveConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ArchiveConfig) Reset() {
	*x = ArchiveConfig{}
	mi := &file_proto_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveConfig) ProtoMessage() {}

func (x *ArchiveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveConfig.ProtoReflect.Descriptor instead.
func (*ArchiveConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{4}
}

func (x *ArchiveConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type OVAConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OVAConfig) Reset() {
	*x = OVAConfig{}
	mi := &file_proto_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OVAConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OVAConfig) ProtoMessage() {}

func (x *OVAConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OVAConfig.ProtoReflect.Descriptor instead.
func (*OVAConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{5}
}

func (x *OVAConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type VDIConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VDIConfig) Reset() {
	*x = VDIConfig{}
	mi := &file_proto_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VDIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VDIConfig) ProtoMessage() {}

func (x *VDIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VDIConfig.ProtoReflect.Descriptor instead.
func (*VDIConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{6}
}

func (x *VDIConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type VMDKConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum file size the plugin will process.
	// If set, this overrides the global max_file_size_bytes configuration
	// for this specific plugin.
	MaxFileSizeBytes int64 `protobuf:"varint,1,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VMDKConfig) Reset() {
	*x = VMDKConfig{}
	mi := &file_proto_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMDKConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMDKConfig) ProtoMessage() {}

func (x *VMDKConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMDKConfig.ProtoReflect.Descriptor instead.
func (*VMDKConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{7}
}

func (x *VMDKConfig) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type HashiCorpVaultValidatorConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL of the Vault server to connect to.
	// https://developer.hashicorp.com/vault
	VaultUrl      string `protobuf:"bytes,1,opt,name=vault_url,json=vaultUrl,proto3" json:"vault_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashiCorpVaultValidatorConfig) Reset() {
	*x = HashiCorpVaultValidatorConfig{}
	mi := &file_proto_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashiCorpVaultValidatorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashiCorpVaultValidatorConfig) ProtoMessage() {}

func (x *HashiCorpVaultValidatorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashiCorpVaultValidatorConfig.ProtoReflect.Descriptor instead.
func (*HashiCorpVaultValidatorConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{8}
}

func (x *HashiCorpVaultValidatorConfig) GetVaultUrl() string {
	if x != nil {
		return x.VaultUrl
	}
	return ""
}

type SDPInspectConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The GCP project id to use for Sensitive Data Protection InspectContent API
	// calls.
	ProjectId     string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SDPInspectConfig) Reset() {
	*x = SDPInspectConfig{}
	mi := &file_proto_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SDPInspectConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDPInspectConfig) ProtoMessage() {}

func (x *SDPInspectConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDPInspectConfig.ProtoReflect.Descriptor instead.
func (*SDPInspectConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{9}
}

func (x *SDPInspectConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type POMXMLNetConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL of the upstream Maven registry.
	UpstreamRegistry string `protobuf:"bytes,1,opt,name=upstream_registry,json=upstreamRegistry,proto3" json:"upstream_registry,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *POMXMLNetConfig) Reset() {
	*x = POMXMLNetConfig{}
	mi := &file_proto_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *POMXMLNetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POMXMLNetConfig) ProtoMessage() {}

func (x *POMXMLNetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POMXMLNetConfig.ProtoReflect.Descriptor instead.
func (*POMXMLNetConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{10}
}

func (x *POMXMLNetConfig) GetUpstreamRegistry() string {
	if x != nil {
		return x.UpstreamRegistry
	}
	return ""
}

var File_proto_config_proto protoreflect.FileDescriptor

const file_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x12proto/config.proto\x12\ascalibr\"\xdc\x01\n" +
	"\fPluginConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\x12%\n" +
	"\x0elocal_registry\x18\x03 \x01(\tR\rlocalRegistry\x12.\n" +
	"\x13disable_google_auth\x18\x04 \x01(\bR\x11disableGoogleAuth\x12F\n" +
	"\x0fplugin_specific\x18\x02 \x03(\v2\x1d.scalibr.PluginSpecificConfigR\x0epluginSpecific\"\xa7\x04\n" +
	"\x14PluginSpecificConfig\x126\n" +
	"\tgo_binary\x18\x01 \x01(\v2\x17.scalibr.GoBinaryConfigH\x00R\bgoBinary\x12>\n" +
	"\vgovulncheck\x18\x02 \x01(\v2\x1a.scalibr.GovulncheckConfigH\x00R\vgovulncheck\x122\n" +
	"\aarchive\x18\x03 \x01(\v2\x16.scalibr.ArchiveConfigH\x00R\aarchive\x12&\n" +
	"\x03ova\x18\x04 \x01(\v2\x12.scalibr.OVAConfigH\x00R\x03ova\x12&\n" +
	"\x03vdi\x18\x05 \x01(\v2\x12.scalibr.VDIConfigH\x00R\x03vdi\x12)\n" +
	"\x04vmdk\x18\x06 \x01(\v2\x13.scalibr.VMDKConfigH\x00R\x04vmdk\x12d\n" +
	"\x19hashicorp_vault_validator\x18\a \x01(\v2&.scalibr.HashiCorpVaultValidatorConfigH\x00R\x17hashicorpVaultValidator\x12<\n" +
	"\vsdp_inspect\x18\b \x01(\v2\x19.scalibr.SDPInspectConfigH\x00R\n" +
	"sdpInspect\x12:\n" +
	"\vpom_xml_net\x18\t \x01(\v2\x18.scalibr.POMXMLNetConfigH\x00R\tpomXmlNetB\b\n" +
	"\x06config\"B\n" +
	"\x0eGoBinaryConfig\x120\n" +
	"\x14version_from_content\x18\x01 \x01(\bR\x12versionFromContent\"D\n" +
	"\x11GovulncheckConfig\x12/\n" +
	"\x14offline_vuln_db_path\x18\x01 \x01(\tR\x11offlineVulnDbPath\">\n" +
	"\rArchiveConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\":\n" +
	"\tOVAConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\":\n" +
	"\tVDIConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\";\n" +
	"\n" +
	"VMDKConfig\x12-\n" +
	"\x13max_file_size_bytes\x18\x01 \x01(\x03R\x10maxFileSizeBytes\"<\n" +
	"\x1dHashiCorpVaultValidatorConfig\x12\x1b\n" +
	"\tvault_url\x18\x01 \x01(\tR\bvaultUrl\"1\n" +
	"\x10SDPInspectConfig\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\">\n" +
	"\x0fPOMXMLNetConfig\x12+\n" +
	"\x11upstream_registry\x18\x01 \x01(\tR\x10upstreamRegistryBFB\x06ConfigP\x01Z:github.com/google/osv-scalibr/binary/proto/config_go_protob\x06proto3"

var (
	file_proto_config_proto_rawDescOnce sync.Once
	file_proto_config_proto_rawDescData []byte
)

func file_proto_config_proto_rawDescGZIP() []byte {
	file_proto_config_proto_rawDescOnce.Do(func() {
		file_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)))
	})
	return file_proto_config_proto_rawDescData
}

var file_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_config_proto_goTypes = []any{
	(*PluginConfig)(nil),                  // 0: scalibr.PluginConfig
	(*PluginSpecificConfig)(nil),          // 1: scalibr.PluginSpecificConfig
	(*GoBinaryConfig)(nil),                // 2: scalibr.GoBinaryConfig
	(*GovulncheckConfig)(nil),             // 3: scalibr.GovulncheckConfig
	(*ArchiveConfig)(nil),                 // 4: scalibr.ArchiveConfig
	(*OVAConfig)(nil),                     // 5: scalibr.OVAConfig
	(*VDIConfig)(nil),                     // 6: scalibr.VDIConfig
	(*VMDKConfig)(nil),                    // 7: scalibr.VMDKConfig
	(*HashiCorpVaultValidatorConfig)(nil), // 8: scalibr.HashiCorpVaultValidatorConfig
	(*SDPInspectConfig)(nil),              // 9: scalibr.SDPInspectConfig
	(*POMXMLNetConfig)(nil),               // 10: scalibr.POMXMLNetConfig
}
var file_proto_config_proto_depIdxs = []int32{
	1,  // 0: scalibr.PluginConfig.plugin_specific:type_name -> scalibr.PluginSpecificConfig
	2,  // 1: scalibr.PluginSpecificConfig.go_binary:type_name -> scalibr.GoBinaryConfig
	3,  // 2: scalibr.PluginSpecificConfig.govulncheck:type_name -> scalibr.GovulncheckConfig
	4,  // 3: scalibr.PluginSpecificConfig.archive:type_name -> scalibr.ArchiveConfig
	5,  // 4: scalibr.PluginSpecificConfig.ova:type_name -> scalibr.OVAConfig
	6,  // 5: scalibr.PluginSpecificConfig.vdi:type_name -> scalibr.VDIConfig
	7,  // 6: scalibr.PluginSpecificConfig.vmdk:type_name -> scalibr.VMDKConfig
	8,  // 7: scalibr.PluginSpecificConfig.hashicorp_vault_validator:type_name -> scalibr.HashiCorpVaultValidatorConfig
	9,  // 8: scalibr.PluginSpecificConfig.sdp_inspect:type_name -> scalibr.SDPInspectConfig
	10, // 9: scalibr.PluginSpecificConfig.pom_xml_net:type_name -> scalibr.POMXMLNetConfig
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_config_proto_init() }
func file_proto_config_proto_init() {
	if File_proto_config_proto != nil {
		return
	}
	file_proto_config_proto_msgTypes[1].OneofWrappers = []any{
		(*PluginSpecificConfig_GoBinary)(nil),
		(*PluginSpecificConfig_Govulncheck)(nil),
		(*PluginSpecificConfig_Archive)(nil),
		(*PluginSpecificConfig_Ova)(nil),
		(*PluginSpecificConfig_Vdi)(nil),
		(*PluginSpecificConfig_Vmdk)(nil),
		(*PluginSpecificConfig_HashicorpVaultValidator)(nil),
		(*PluginSpecificConfig_SdpInspect)(nil),
		(*PluginSpecificConfig_PomXmlNet)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_config_proto_goTypes,
		DependencyIndexes: file_proto_config_proto_depIdxs,
		MessageInfos:      file_proto_config_proto_msgTypes,
	}.Build()
	File_proto_config_proto = out.File
	file_proto_config_proto_goTypes = nil
	file_proto_config_proto_depIdxs = nil
}
