name: prp-issue-workflow
on:
  issues:
    types: [labeled]
jobs:
  on-request-post-welcome:
    if: github.event.label.name == 'PRP:Request'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      GH_OWNER: ${{ github.repository_owner }}
      GH_REPO_NAME: ${{ github.event.repository.name }}
      NUMBER: ${{ github.event.issue.number }}
      AUTHOR: ${{ github.event.issue.user.login }}
    steps:
      - name: Post comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          BODY: |
              Welcome to the OSV-SCALIBR patch reward program!
              Your issue has been added to our triage queue and will reviewed
              shortly. The panel usually takes a decision once per week, so it
              can take up to a week before you hear back from us.
              Please, do not start the work until the panel has reached a
              decision. Although we always welcome contributions, unapproved
              work is not eligible for a reward.
              *~The OSV-SCALIBR PRP team*
      - name: Assign to author
        continue-on-error: true
        run: gh issue edit "$NUMBER" --add-assignee "$AUTHOR"
  on-accepted-post-doc:
    if: github.event.label.name == 'PRP:Accepted'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      NUMBER: ${{ github.event.issue.number }}
      AUTHOR: ${{ github.event.issue.user.login }}
    steps:
      - name: Post comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          BODY: |
              Congratulations, your request has been approved! 🎉
              This means that you can start working on this contribution.
              ❗ Please take a moment to fill the [participation form](https://bughunters.google.com/report/tsunami)
              If you are unsure where to start, we have compiled a set of
              useful guides in our documentation:
              * [Writing a new vulnerability detector plugin](https://github.com/google/osv-scalibr/blob/main/docs/new_detector.md)
              * [Writing a new inventory extraction plugin](https://github.com/google/osv-scalibr/blob/main/docs/new_extractor.md)
              * [Main directory for secret detectors](https://github.com/google/osv-scalibr/tree/main/veles) - More detailed docs will be available soon!
              * [General style guide](https://github.com/google/osv-scalibr/blob/main/docs/style_guide.md)

              *~The OSV-SCALIBR PRP team*
  on-queue-post-explanation:
    if: github.event.label.name == 'Contributor queue'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      NUMBER: ${{ github.event.issue.number }}
      AUTHOR: ${{ github.event.issue.user.login }}
    steps:
      - name: Post comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          BODY: |
              This issue has been put in your contributor queue. This usually
              means that you already are working on a contribution and the
              panel is waiting for your other contributions to be fully
              merged.
              An issue in your queue is not pre-approved. Any issue that is
              not explicitely approved by the panel will not be eligible for
              a reward.
              Unless there is an emergency, an issue in your queue cannot be
              claimed by another contributor.
              *~The OSV-SCALIBR PRP team*
